spring.application.name=streamSphere


spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=Springstudent1@

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=TAi1G*J3F*sdBL97_APK

spring.redis.host=localhost
spring.redis.port=6379

